version: '4'
services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'